<!DOCTYPE MLDB [
	<!ELEMENT MLDB	(MEMBER, WEB_CATE, CCTV_INFO+, CATE+, REGION+ , P_CNT+)>

<!--  XML SYSTEM ENTITY
&amp;  -  &
&apos;  -  '
&gt  -  >
&lt  -  <
&quot  -  "
 -->
	<!--  TABLE MEMBER            -->
	<!ELEMENT MEMBER (MEM_NO, MEM_NAME, PERM, PASS, ID, EMAIL, AUTH, PASS_INSTANCE, ACTIVE_YN, MEM_UP_DATE*)>
  <!ATTLIST MEMBER IN_DATE CDATA  #REQUIRED>
	<!ELEMENT MEM_NO			(#PCDATA)>
	<!ELEMENT MEM_NAME			(#PCDATA)>
	<!ELEMENT PERM			(#PCDATA)>
	<!ELEMENT PASS			(#PCDATA)>
	<!ELEMENT ID			(#PCDATA)>
	<!ELEMENT EMAIL			(#PCDATA)>
	<!ELEMENT AUTH			(#PCDATA)>
	<!ELEMENT PASS_INSTANCE			(#PCDATA)>
	<!ELEMENT ACTIVE_YN			(#PCDATA)>
	<!ELEMENT MEM_UP_DATE			(#PCDATA)>
  <!ATTLIST MEM_UP_DATE REASON CDATA  #REQUIRED>

	<!--  TABLE WEB_CATE            -->
	<!ELEMENT WEB_CATE (MENU_NO, MENU_NAME, MENU_PERM, PARENT_NO, URI, MENU_USE_YN, MENU_UP_DATE*)>
	<!ATTLIST WEB_CATE IN_DATE CDATA  #REQUIRED>
	<!ELEMENT MENU_NO			(#PCDATA)>
	<!ELEMENT MENU_NAME			(#PCDATA)>
	<!ELEMENT MENU_PERM			(#PCDATA)>
	<!ELEMENT PARENT_NO			(#PCDATA)>
	<!ELEMENT URI			(#PCDATA)>
	<!ELEMENT MENU_USE_YN			(#PCDATA)>
	<!ELEMENT MENU_UP_DATE			(#PCDATA)>
  <!ATTLIST MENU_UP_DATE REASON CDATA  #REQUIRED>
  
  <!ELEMENT CCTV_INFO (CCTV_UUID,CCTV_NAME,CCTV_TYPE,CCTV_RESOLUTION,CCTV_MARKER,CCTV_UPDATE*,CCTV_USE_YN)>
	<!ATTLIST CCTV_INFO IN_DATE CDATA #REQUIRED>
	<!ELEMENT CCTV_UUID (#PCDATA)>
	<!ELEMENT CCTV_NAME (#PCDATA)>
	<!ELEMENT CCTV_TYPE (#PCDATA)>
	<!ELEMENT CCTV_RESOLUTION (#PCDATA)>
	<!ELEMENT CCTV_MARKER (#PCDATA)>
	<!ELEMENT CCTV_UPDATE (#PCDATA)>
	<!ELEMENT CCTV_USE_YN (#PCDATA)>
	
<!ELEMENT CATE (CATE_UUID,CATE_NAME,CATE_TYPE,CATE_CONTENTS,CATE_UPDATE*,CATE_USE_YN)>
	<!ATTLIST CATE IN_DATE CDATA #REQUIRED>
	<!ELEMENT CATE_UUID (#PCDATA)>
	<!ELEMENT CATE_NAME (#PCDATA)>
	<!ELEMENT CATE_TYPE (#PCDATA)>
	<!ELEMENT CATE_CONTENTS (#PCDATA)>
	<!ELEMENT CATE_UPDATE (#PCDATA)>
	<!ELEMENT CATE_USE_YN (#PCDATA)>
		
<!ELEMENT REGION (REGION_UUID,REGION_NAME,REGION_ADDR,REGION_POSTNUM,(REGION_NATION | REGION_NATIONCODE),REGION_UPDATE*,REGION_USE_YN)>
	<!ATTLIST REGION IN_DATE CDATA #REQUIRED>
	<!ELEMENT REGION_UUID (#PCDATA)>
	<!ELEMENT REGION_NAME (#PCDATA)>
	<!ELEMENT REGION_ADDR (#PCDATA)>
	<!ELEMENT REGION_POSTNUM (#PCDATA)>
	<!ELEMENT REGION_NATION (#PCDATA)>
	<!ELEMENT REGION_NATIONCODE (#PCDATA)>
	<!ELEMENT REGION_UPDATE (#PCDATA)>
	<!ELEMENT REGION_USE_YN (#PCDATA)>
	
	
<!ELEMENT P_CNT (P_CNT_UUID,P_CNT_NAME,P_CNT_PRE_CNT,P_CNT_COUNT,P_CNT_REGION_UUID,P_CNT_CATE_UUID,P_CNT_UPDATE*,P_CNT_USE_YN)>
	<!ATTLIST P_CNT IN_DATE CDATA #REQUIRED>
	<!ELEMENT P_CNT_UUID (#PCDATA)>
	<!ELEMENT P_CNT_NAME (#PCDATA)>
	<!ELEMENT P_CNT_PRE_CNT (#PCDATA)>
	<!ELEMENT P_CNT_COUNT (#PCDATA)>
	<!ELEMENT P_CNT_REGION_UUID (#PCDATA)>
	<!ELEMENT P_CNT_CATE_UUID (#PCDATA)>
	<!ELEMENT P_CNT_UPDATE (#PCDATA)>
	<!ATTLIST P_CNT_UPDATE REASON CDATA #REQUIRED>
	<!ELEMENT P_CNT_USE_YN (#PCDATA)>
	
]>


<MLDB>

	<MEMBER IN_DATE="2022-02-03 04:01:01">
		 <MEM_NO>0</MEM_NO>
		 <MEM_NAME>super user</MEM_NAME>
		 <PERM>9</PERM>
		 <PASS>dslfs5ds8f79wEWEGERERH8DFGDR8</PASS>
		 <ID>admin</ID>
		 <EMAIL>admin@hiseoullearn.com</EMAIL>
		 <AUTH>0</AUTH>
		 <PASS_INSTANCE>N</PASS_INSTANCE>
		 <ACTIVE_YN>Y</ACTIVE_YN>
		 <MEM_UP_DATE			REASON="INSTANCE PASS ISSUE"></MEM_UP_DATE>
	 </MEMBER>
	 <MEMBER IN_DATE="2022-02-03 04:05:01">
 		 <MEM_NO>1</MEM_NO>
 		 <MEM_NAME>user</MEM_NAME>
 		 <PERM>1</PERM>
 		 <PASS>RFSJDGF708DFHD9464556756GDR8</PASS>
 		 <ID>user</ID>
 		 <EMAIL>user@hiseoullearn.com</EMAIL>
 		 <AUTH>0</AUTH>
 		 <PASS_INSTANCE>N</PASS_INSTANCE>
 		 <ACTIVE_YN>Y</ACTIVE_YN>
 		 <MEM_UP_DATE			REASON="INSTANCE PASS ISSUE"></MEM_UP_DATE>
 	 </MEMBER>
	
	 <WEB_CATE IN_DATE="0000-00-00 00:00:00">
		 	<MENU_NO>0</MENU_NO>
		 	<MENU_NAME>DASHBOARD</MENU_NAME>
		 	<MENU_PERM>1</MENU_PERM>
		 	<PARENT_NO>0</PARENT_NO>
		 	<URI>192.168.40.132/WEB</URI>
		 	<MENU_USE_YN>Y</MENU_USE_YN>
		 	<MENU_UP_DATE REASON="DEFAULT"></MENU_UP_DATE>
   </WEB_CATE>
	
	 <WEB_CATE IN_DATE="0000-00-00 00:00:00">
		 	<MENU_NO>1</MENU_NO>
		 	<MENU_NAME>MLVIEW</MENU_NAME>
		 	<MENU_PERM>1</MENU_PERM>
		 	<PARENT_NO>0</PARENT_NO>
		 	<URI>192.168.40.132/WEB/MLVIEW</URI>
		 	<MENU_USE_YN>Y</MENU_USE_YN>
		 	<MENU_UP_DATE REASON="DEFAULT"></MENU_UP_DATE>
   </WEB_CATE>
	
	 <WEB_CATE IN_DATE="0000-00-00 00:00:00">
		 	<MENU_NO>2</MENU_NO>
		 	<MENU_NAME>NOTICE</MENU_NAME>
		 	<MENU_PERM>1</MENU_PERM>
		 	<PARENT_NO>0</PARENT_NO>
		 	<URI>192.168.40.132/WEB/NOTICE</URI>
		 	<MENU_USE_YN>Y</MENU_USE_YN>
		 	<MENU_UP_DATE REASON="DEFAULT"></MENU_UP_DATE>
   </WEB_CATE>
	
	 <CCTV_INFO IN_DATE="2022-02-03">
		 <CCTV_UUID>JASDFOADJASODGADGLJOAI7SDG8SYG9SSDYGS9</CCTV_UUID>
		 <CCTV_NAME>SONY N 87868 VDS NO 10</CCTV_NAME>
		 <CCTV_TYPE>LOAD CAM</CCTV_TYPE>
		 <CCTV_RESOLUTION>1280 X 640</CCTV_RESOLUTION>
		 <CCTV_MARKER>PEOPLE COUNTS</CCTV_MARKER>
		 <CCTV_UPDATE>2022-02-03 09:11:01</CCTV_UPDATE>
		 <CCTV_UPDATE>2022-02-03 09:14:22</CCTV_UPDATE>
		 <CCTV_UPDATE>2022-02-03 11:23:01</CCTV_UPDATE>
		 <CCTV_UPDATE>2022-02-03 15:34:33</CCTV_UPDATE>
		 <CCTV_USE_YN>Y</CCTV_USE_YN>
	 </CCTV_INFO>
	 <CCTV_INFO IN_DATE="2022-02-05">
		 <CCTV_UUID>JASDFOADJASODGADGLJOAIETER43G34T34T344</CCTV_UUID>
		 <CCTV_NAME>SONY N 87868 VDS NO 11</CCTV_NAME>
		 <CCTV_TYPE>LOAD CAM</CCTV_TYPE>
		 <CCTV_RESOLUTION>1280 X 640</CCTV_RESOLUTION>
		 <CCTV_MARKER>PEOPLE COUNTS</CCTV_MARKER>
		 <CCTV_UPDATE>2022-02-05 09:11:01</CCTV_UPDATE>
		 <CCTV_UPDATE>2022-02-05 09:14:22</CCTV_UPDATE>
		 <CCTV_USE_YN>Y</CCTV_USE_YN>
	 </CCTV_INFO>
	
	 <CATE IN_DATE="2022-02-05">
		 	<CATE_UUID>DLSJALJFIEOJDJFLJDSLFSLDSDF80FA89S0DF</CATE_UUID>
		 	<CATE_NAME>PEOPLE COUNT DEAGU SUBWAY1</CATE_NAME>
		 	<CATE_TYPE>OPENCV YOLO  1 &gt; 3</CATE_TYPE>
		 	<CATE_CONTENTS>DEAGU SUBWAY LINE 1 OPENCV PEOPLE COUNT ML</CATE_CONTENTS>
		 	<CATE_UPDATE>2022-02-05 09:11:01</CATE_UPDATE>
		 	<CATE_USE_YN>Y</CATE_USE_YN>
	 </CATE>
	 
	 <REGION IN_DATE="2022-02-05">
		 	<REGION_UUID>KLHLKJHGSRKGFH3454YH5354Y34T3T34T34T</REGION_UUID>
		 	<REGION_NAME>KOREA DEAGU</REGION_NAME>
		 	<REGION_ADDR>KOREA DEAGUSI DEACHUNGU DEACHUNDONG 123</REGION_ADDR>
		 	<REGION_POSTNUM>121355</REGION_POSTNUM>
		 	<REGION_NATION>KO</REGION_NATION>
		 	<REGION_NATIONCODE>82</REGION_NATIONCODE>
		 	<REGION_UPDATE>2022-02-05 09:11:01</REGION_UPDATE>
		 	<REGION_USE_YN>Y</REGION_USE_YN>
	 </REGION>
	 
	 <P_CNT	IN_DATE="2022-02-05">
		 	<P_CNT_UUID>DFGUETIYJ5Y54Y45Y45Y45Y45Y45Y45Y45Y4</P_CNT_UUID>
		 	<P_CNT_NAME>DK000211</P_CNT_NAME>
		 	<P_CNT_PRE_CNT>22</P_CNT_PRE_CNT>
		 	<P_CNT_COUNT>12</P_CNT_COUNT>
		 	<P_CNT_REGION_UUID>KLHLKJHGSRKGFH3454YH5354Y34T3T34T34T</P_CNT_REGION_UUID>
		 	<P_CNT_CATE_UUID>JASDFOADJASODGADGLJOAIETER43G34T34T344</P_CNT_CATE_UUID>
		 	<P_CNT_UPDATE	REASON="INITS">2022-02-05 11:23:01</P_CNT_UPDATE>
			<P_CNT_UPDATE	REASON="RECHECK01">2022-02-05 12:23:01</P_CNT_UPDATE>
		 	<P_CNT_USE_YN>Y</P_CNT_USE_YN>
		</P_CNT>
</MLDB>