<!DOCTYPE MLDB[

<!ELEMENT MLDB (MEMBER+, WEB_CATE+,CCTV_INFO+,CATE+,REGION+,P_CNT+)>

<!ELEMENT MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_HP,MEMBER_EMAIL,MEMBER_NAME,MEMBER_CHECK,MEMBER_FAIL,MEMBER_WARNING,MEMBER_OK)>
	<!ATTLIST MEMBER IN_DATE CDATA #REQUIRED>
	<!ELEMENT MEMBER_ID (#PCDATA)>
	<!ELEMENT MEMBER_PW (#PCDATA)>
	<!ELEMENT MEMBER_HP (#PCDATA)>
	<!ELEMENT MEMBER_EMAIL (#PCDATA)>
	<!ELEMENT MEMBER_NAME (#PCDATA)>
	<!ELEMENT MEMBER_CHECK (#PCDATA)>
	<!ELEMENT MEMBER_FAIL (#PCDATA)>
	<!ELEMENT MEMBER_WARNING (#PCDATA)>
	<!ELEMENT MEMBER_OK (#PCDATA)>
	
	
<!ELEMENT WEB_CATE (WEB_NAME,WEB_CHECK,WEB_ID,WEB_PW,WEB_NOTICE,WEB_UPDATE,CCTV_BUTTON)>
	<!ATTLIST WEB_CATE IN_DATE CDATA #REQUIRED>
	<!ELEMENT WEB_NAME (#PCDATA)>
	<!ELEMENT WEB_CHECK (#PCDATA)>
	<!ELEMENT WEB_ID (#PCDATA)>
	<!ELEMENT WEB_PW (#PCDATA)>
	<!ELEMENT WEB_NOTICE (#PCDATA)>
	<!ELEMENT WEB_UPDATE (#PCDATA)>
	<!ELEMENT CCTV_BUTTON (#PCDATA)>

<!ELEMENT CCTV_INFO (CCTV_UUID,CCTV_NAME,CCTV_TYPE,CCTV_RESOLUTION,CCTV_MARKER,CCTV_UPDATE*,CCTV_USE_YN)>
	<!ATTLIST CCTV_INFO IN_DATE CDATA #REQUIRED>
	<!ELEMENT CCTV_UUID (#PCDATA)>
	<!ELEMENT CCTV_NAME (#PCDATA)>
	<!ELEMENT CCTV_TYPE (#PCDATA)>
	<!ELEMENT CCTV_RESOLUTION (#PCDATA)>
	<!ELEMENT CCTV_MARKER (#PCDATA)>
	<!ELEMENT CCTV_UPDATE (#PCDATA)>
	<!ELEMENT CCTV_USE_YN (#PCDATA)>
	
<!ELEMENT CATE (CATE_UUID,CATE_NAME,CATE_TYPE,CATE_CONTENTS,CATE_UPDATE*,CATE_USE_YN)>
	<!ATTLIST CATE IN_DATE CDATA #REQUIRED>
	<!ELEMENT CATE_UUID (#PCDATA)>
	<!ELEMENT CATE_NAME (#PCDATA)>
	<!ELEMENT CATE_TYPE (#PCDATA)>
	<!ELEMENT CATE_CONTENTS (#PCDATA)>
	<!ELEMENT CATE_UPDATE (#PCDATA)>
	<!ELEMENT CATE_USE_YN (#PCDATA)>
		
<!ELEMENT REGION (REGION_UUID,REGION_NAME,REGION_ADDR,REGION_POSTNUM,(REGION_NATION | REGION_NATIONCODE),REGION_UPDATE*,REGION_USE_YN)>
	<!ATTLIST REGION IN_DATE CDATA #REQUIRED>
	<!ELEMENT REGION_UUID (#PCDATA)>
	<!ELEMENT REGION_NAME (#PCDATA)>
	<!ELEMENT REGION_ADDR (#PCDATA)>
	<!ELEMENT REGION_POSTNUM (#PCDATA)>
	<!ELEMENT REGION_NATION (#PCDATA)>
	<!ELEMENT REGION_NATIONCODE (#PCDATA)>
	<!ELEMENT REGION_UPDATE (#PCDATA)>
	<!ELEMENT REGION_USE_YN (#PCDATA)>
	
	
<!ELEMENT P_CNT (P_CNT_UUID,P_CNT_NAME,P_CNT_PRE_CNT,P_CNT_COUNT,P_CNT_REGION_UUID,P_CNT_CATE_UUID,P_CNT_UPDATE*,P_CNT_USE_YN)>
	<!ATTLIST P_CNT IN_DATE CDATA #REQUIRED>
	<!ELEMENT P_CNT_UUID (#PCDATA)>
	<!ELEMENT P_CNT_NAME (#PCDATA)>
	<!ELEMENT P_CNT_PRE_CNT (#PCDATA)>
	<!ELEMENT P_CNT_COUNT (#PCDATA)>
	<!ELEMENT P_CNT_REGION_UUID (#PCDATA)>
	<!ELEMENT P_CNT_CATE_UUID (#PCDATA)>
	<!ELEMENT P_CNT_UPDATE (#PCDATA)>
	<!ELEMENT P_CNT_USE_YN (#PCDATA)>
	
]>

<MLDB>
	<MEMBER IN_DATE="2022-02-11">
		<MEMBER_ID>하이</MEMBER_ID>
		<MEMBER_PW>하이</MEMBER_PW>
		<MEMBER_HP>하이</MEMBER_HP>
		<MEMBER_EMAIL>하이</MEMBER_EMAIL>
		<MEMBER_NAME>하이</MEMBER_NAME>
		<MEMBER_CHECK>하이</MEMBER_CHECK>
		<MEMBER_FAIL>하이</MEMBER_FAIL>
		<MEMBER_WARNING>하이</MEMBER_WARNING>
		<MEMBER_OK>하이</MEMBER_OK>
	</MEMBER>
	
	<WEB_CATE IN_DATE="2022-02-11">
		<WEB_NAME>하이</WEB_NAME>
		<WEB_CHECK>하이</WEB_CHECK>
		<WEB_ID>하이</WEB_ID>
		<WEB_PW>하이</WEB_PW>
		<WEB_NOTICE>하이</WEB_NOTICE>
		<WEB_UPDATE>하이</WEB_UPDATE>
		<CCTV_BUTTON>하이</CCTV_BUTTON>
	</WEB_CATE>
	
	<CCTV_INFO IN_DATE="2022-02-11" >
		<CCTV_UUID>하이</CCTV_UUID>
		<CCTV_NAME>하이</CCTV_NAME>
		<CCTV_TYPE>하이</CCTV_TYPE>
		<CCTV_RESOLUTION>하이</CCTV_RESOLUTION>
		<CCTV_MARKER>하이</CCTV_MARKER>
		<CCTV_UPDATE>하이</CCTV_UPDATE>
		<CCTV_USE_YN>하이</CCTV_USE_YN>
	</CCTV_INFO>
	
	<CATE IN_DATE="2022-02-11">
		<CATE_UUID>하이</CATE_UUID>
		<CATE_NAME>하이</CATE_NAME>
		<CATE_TYPE>하이</CATE_TYPE>
		<CATE_CONTENTS>하이</CATE_CONTENTS>
		<CATE_UPDATE>하이</CATE_UPDATE>
		<CATE_USE_YN>하이</CATE_USE_YN>
	</CATE>
	
	<REGION IN_DATE="2022-02-11">
		<REGION_UUID>하이</REGION_UUID>
		<REGION_NAME>하이</REGION_NAME>
		<REGION_ADDR>하이</REGION_ADDR>
		<REGION_POSTNUM>하이</REGION_POSTNUM>
		<REGION_NATION>하이</REGION_NATION>
		<REGION_NATIONCODE>하이</REGION_NATIONCODE>
		<REGION_UPDATE>하이</REGION_UPDATE>
		<REGION_UPDATE>헬로</REGION_UPDATE>
		<REGION_USE_YN>하이</REGION_USE_YN>
	</REGION>

	<P_CNT IN_DATE="2022-02-11">
		<P_CNT_UUID>하이</P_CNT_UUID>
		<P_CNT_NAME>하이</P_CNT_NAME>
		<P_CNT_PRE_CNT>하이</P_CNT_PRE_CNT>
		<P_CNT_COUNT>하이</P_CNT_COUNT>
		<P_CNT_REGION_UUID>하이</P_CNT_REGION_UUID>
		<P_CNT_CATE_UUID>하이</P_CNT_CATE_UUID>
		<P_CNT_UPDATE>하이</P_CNT_UPDATE>
		<P_CNT_USE_YN>하이</P_CNT_USE_YN>
	</P_CNT>
	

</MLDB>
